version: '3.3'

services:
  master:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/tcp.conf:/etc/nginx/tcp.conf
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build:
      context: .
      dockerfile: dockerfile
    # ports:
    #   - "3000:80"
    environment:
      - CONTAINERID=server1
      - PORT=5001
    env_file:
      - .env
      
  server2:
    build:
      context: .
      dockerfile: dockerfile
    # ports:
    #   - "3001:80"
    environment:
      - CONTAINERID=server2
      - PORT=5002
    env_file:
      - .env

  server3:
    build:
      context: .
      dockerfile: dockerfile
    # ports:
    #   - "3001:80"
    environment:
      - CONTAINERID=server3
      - PORT=5003
    env_file:
      - .env


