version: '3.7'

services:

  server1:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:80"
    environment:
      - APPID=server1
  server2:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5001:80"
    environment:
      - APPID=server2


